python edit_video.py \
    --video-size 512 512 \
    --video-length 25 \
    --infer-steps 30 \
    --inject 5 \
    --seed 42 \
    --embedded-cfg-scale 2 \
    --flow-shift 7.0 \
    --flow-reverse \
    --use-cpu-offload \
    --use-fp8 \
    --save-path ./results/V2VBench/rf-solver_2order \
    --dataset "V2VBench"